### ISSUE TITLE
Error after page loads: AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by ItzJustError** [NightfallGT/Discord-QR-Scam#37]
Hello, I have an issue. When the discord log-in page loads, it prompts me with `AttributeError: 'NoneType' object has no attribute 'find'`
![screenshot](https://user-images.githubusercontent.com/81372439/210848979-940fcbd7-0921-45e7-a4df-c74705f11880.png)

**Comment by KeenAttic** [comment]
I have such a problem, could you solve it? And if so, please tell me how to solve it
