### ISSUE TITLE
Discord will catch your scam!

### ISSUE THREAD

**Issue by CA1R7** [NightfallGT/Discord-QR-Scam#7]
😒 But if you sent the gift to someone, Discord automatically will notify to the victim below :
![](https://cdn.discordapp.com/attachments/667100630820847618/669322222925512704/image0.png)

**Comment by GlUTEN-BASH** [comment]
Ok, and? Nobody really cares yno, everybody just clicking yes

**Comment by KliqxTV** [comment]
Agreeing with @GlUTEN-BASH
This is a pretty obvious scam to begin with and, because of that, targeted at rather gullible people that just scan random QR codes and blindly spam on "yes" buttons...

**Comment by GlUTEN-BASH** [comment]
@KliqxTV close this issue pls, its not even the issue with code

**Comment by GlUTEN-BASH** [comment]
@KliqxTV sry, i forgot where this issue was posted

**Comment by KliqxTV** [comment]
@GlUTEN-BASH I would if I could, I'm not this repo's author, was about to say 😂

**Comment by CA1R7** [comment]
@GlUTEN-BASH I agree cuz peoples does not care, When they see the button automatically will click to 'yes' 🤣, Good scam!
